version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "security"]
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers: ["supraluminix-creator"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "ci"]
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers: ["supraluminix-creator"]
