from typing import Protocol, TypeVar, Generic, Iterator, Any, Optional

K = TypeVar("K")
V = TypeVar("V")

class Cache(Generic[K, V]):
    def __init__(self, directory: str = ..., timeout: int | None = ...) -> None: ...
    def get(self, key: K, default: V | None = ...) -> V | None: ...
    def set(self, key: K, value: V, expire: int | None = ...) -> None: ...
    def close(self) -> None: ...
    def clear(self) -> None: ...

__all__ = ["Cache"]
