from typing import Any, TypeVar

_K = TypeVar("_K")
_V = TypeVar("_V")

class Cache:
    def __init__(self, directory: str, *args: Any, **kwargs: Any) -> None: ...
    def __contains__(self, key: _K) -> bool: ...
    def __len__(self) -> int: ...
    def get(self, key: _K, default: _V | None = None) -> _V | None: ...
    def set(self, key: _K, value: _V, expire: int | None = None) -> bool: ...
    def clear(self) -> None: ...
    def close(self) -> None: ...
